%% <module> skos
% Autogenerated by rdfs2pl
% Example: swipl....

:-module(skos,[collection/1,concept/1,concept_Scheme/1,ordered_Collection/1,alternative_label/2,has_broader_match/2,has_broader/2,has_broader_transitive/2,change_note/2,has_close_match/2,definition/2,editorial_note/2,has_exact_match/2,example/2,has_top_concept/2,hidden_label/2,history_note/2,is_in_scheme/2,is_in_mapping_relation_with/2,has_member/2,has_member_list/2,has_narrower_match/2,has_narrower/2,has_narrower_transitive/2,notation/2,note/2,preferred_label/2,has_related/2,has_related_match/2,scope_note/2,is_in_semantic_relation_with/2,is_top_concept_in_scheme/2,op(300,xfy,alternative_label),op(300,xfy,has_broader_match),op(300,xfy,has_broader),op(300,xfy,has_broader_transitive),op(300,xfy,change_note),op(300,xfy,has_close_match),op(300,xfy,definition),op(300,xfy,editorial_note),op(300,xfy,has_exact_match),op(300,xfy,example),op(300,xfy,has_top_concept),op(300,xfy,hidden_label),op(300,xfy,history_note),op(300,xfy,is_in_scheme),op(300,xfy,is_in_mapping_relation_with),op(300,xfy,has_member),op(300,xfy,has_member_list),op(300,xfy,has_narrower_match),op(300,xfy,has_narrower),op(300,xfy,has_narrower_transitive),op(300,xfy,notation),op(300,xfy,note),op(300,xfy,preferred_label),op(300,xfy,has_related),op(300,xfy,has_related_match),op(300,xfy,scope_note),op(300,xfy,is_in_semantic_relation_with),op(300,xfy,is_top_concept_in_scheme)]).
:-use_module(library(semweb/rdf_db)).
:-use_module(library(semweb/rdfs)).

:-op(300,xfy,alternative_label).
:-op(300,xfy,has_broader_match).
:-op(300,xfy,has_broader).
:-op(300,xfy,has_broader_transitive).
:-op(300,xfy,change_note).
:-op(300,xfy,has_close_match).
:-op(300,xfy,definition).
:-op(300,xfy,editorial_note).
:-op(300,xfy,has_exact_match).
:-op(300,xfy,example).
:-op(300,xfy,has_top_concept).
:-op(300,xfy,hidden_label).
:-op(300,xfy,history_note).
:-op(300,xfy,is_in_scheme).
:-op(300,xfy,is_in_mapping_relation_with).
:-op(300,xfy,has_member).
:-op(300,xfy,has_member_list).
:-op(300,xfy,has_narrower_match).
:-op(300,xfy,has_narrower).
:-op(300,xfy,has_narrower_transitive).
:-op(300,xfy,notation).
:-op(300,xfy,note).
:-op(300,xfy,preferred_label).
:-op(300,xfy,has_related).
:-op(300,xfy,has_related_match).
:-op(300,xfy,scope_note).
:-op(300,xfy,is_in_semantic_relation_with).
:-op(300,xfy,is_top_concept_in_scheme).

:-rdf_meta skos:collection(r).
:-rdf_meta skos:concept(r).
:-rdf_meta skos:concept_Scheme(r).
:-rdf_meta skos:ordered_Collection(r).
:-rdf_meta skos:alternative_label(r,r).
:-rdf_meta skos:change_note(r,r).
:-rdf_meta skos:definition(r,r).
:-rdf_meta skos:editorial_note(r,r).
:-rdf_meta skos:example(r,r).
:-rdf_meta skos:has_broader(r,r).
:-rdf_meta skos:has_broader_match(r,r).
:-rdf_meta skos:has_broader_transitive(r,r).
:-rdf_meta skos:has_close_match(r,r).
:-rdf_meta skos:has_exact_match(r,r).
:-rdf_meta skos:has_member(r,r).
:-rdf_meta skos:has_member_list(r,r).
:-rdf_meta skos:has_narrower(r,r).
:-rdf_meta skos:has_narrower_match(r,r).
:-rdf_meta skos:has_narrower_transitive(r,r).
:-rdf_meta skos:has_related(r,r).
:-rdf_meta skos:has_related_match(r,r).
:-rdf_meta skos:has_top_concept(r,r).
:-rdf_meta skos:hidden_label(r,r).
:-rdf_meta skos:history_note(r,r).
:-rdf_meta skos:is_in_mapping_relation_with(r,r).
:-rdf_meta skos:is_in_scheme(r,r).
:-rdf_meta skos:is_in_semantic_relation_with(r,r).
:-rdf_meta skos:is_top_concept_in_scheme(r,r).
:-rdf_meta skos:notation(r,-).
:-rdf_meta skos:notation(r,r).
:-rdf_meta skos:note(r,r).
:-rdf_meta skos:preferred_label(r,r).
:-rdf_meta skos:scope_note(r,r).
skos:collection(A):-rdfs_individual_of(A,'http://www.w3.org/2004/02/skos/core#Collection').
skos:concept(A):-rdfs_individual_of(A,'http://www.w3.org/2004/02/skos/core#Concept').
skos:concept_Scheme(A):-rdfs_individual_of(A,'http://www.w3.org/2004/02/skos/core#ConceptScheme').
skos:ordered_Collection(A):-rdfs_individual_of(A,'http://www.w3.org/2004/02/skos/core#OrderedCollection').
skos:alternative_label(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#altLabel',B).
skos:change_note(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#changeNote',B).
skos:definition(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#definition',B).
skos:editorial_note(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#editorialNote',B).
skos:example(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#example',B).
skos:has_broader(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#broader',B).
skos:has_broader(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#broader',B).
skos:has_broader_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#broadMatch',B).
skos:has_broader_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#broadMatch',B).
skos:has_broader_transitive(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#broaderTransitive',B).
skos:has_broader_transitive(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#broaderTransitive',B).
skos:has_close_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#closeMatch',B).
skos:has_close_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#closeMatch',B).
skos:has_exact_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#exactMatch',B).
skos:has_exact_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#exactMatch',B).
skos:has_member(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#member',B).
skos:has_member(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#member',B).
skos:has_member_list(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#memberList',B).
skos:has_member_list(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#memberList',B).
skos:has_narrower(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#narrower',B).
skos:has_narrower(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#narrower',B).
skos:has_narrower_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#narrowMatch',B).
skos:has_narrower_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#narrowMatch',B).
skos:has_narrower_transitive(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#narrowerTransitive',B).
skos:has_narrower_transitive(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#narrowerTransitive',B).
skos:has_related(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#related',B).
skos:has_related(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#related',B).
skos:has_related_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#relatedMatch',B).
skos:has_related_match(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#relatedMatch',B).
skos:has_top_concept(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#hasTopConcept',B).
skos:has_top_concept(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#hasTopConcept',B).
skos:hidden_label(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#hiddenLabel',B).
skos:history_note(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#historyNote',B).
skos:is_in_mapping_relation_with(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#mappingRelation',B).
skos:is_in_mapping_relation_with(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#mappingRelation',B).
skos:is_in_scheme(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#inScheme',B).
skos:is_in_scheme(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#inScheme',B).
skos:is_in_semantic_relation_with(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#semanticRelation',B).
skos:is_in_semantic_relation_with(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#semanticRelation',B).
skos:is_top_concept_in_scheme(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#topConceptOf',B).
skos:is_top_concept_in_scheme(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#topConceptOf',B).
skos:notation(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#notation',B).
skos:notation(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#notation',C),rdf_literal_value(C,B).
skos:note(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#note',B).
skos:preferred_label(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#prefLabel',B).
skos:scope_note(A,B):-rdf_has(A,'http://www.w3.org/2004/02/skos/core#scopeNote',B).
